import Head from 'next/head'
import Banner2 from '../Components/Banner2'
import Bienetre from '../Components/Bienetre'
import ContactButton from '../Components/ContactButton'
import Footer from '../Components/Footer'



export default function Methodes() {
  return (
    <div>
      <Head>
        <title>Prasana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner2/>
            <ContactButton/>
            {/* ici les composant de la page */}
            <Bienetre/>
        <Footer/>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}