import Head from 'next/head'
import Banner2 from '../Components/Banner2'
import Bowen from '../Components/Bowen'
import Footer from '../Components/Footer'
import Kinesiologie from '../Components/Kinesiologie'



export default function Methodes() {
  return (
    <div>
      <Head>
        <title>Prasana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner2/>
            {/* ici les composant de la page */}
            <Kinesiologie/>
            <Bowen/>
        <Footer/>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}